---
- name: Create service directory
  file:
    path: '{{ codex_data_folder }}'
    state: directory
    owner: '{{ codex_user }}'
    group: '{{ codex_group }}'
    mode: 0770

- name: Create helper scripts
  template:
    src: '{{ item }}'
    dest: '{{ codex_service_path }}/{{ item|basename|replace(".j2", "") }}'
    owner: '{{ codex_user }}'
    group: '{{ codex_group }}'
    mode: 0750
  with_fileglob:
    - 'templates/scripts/*'
